### PR TITLE
Add encap example for GTP PDU session container.

### PR DESCRIPTION
**Pull request by ShiriKuzin**
Signed-off-by: Shiri Kuzin <shirik@nvidia.com>

### CODE REVIEW

**Review by jackmin — CHANGES_REQUESTED** [review]
Hey,
(I don't know why I cannot inline comments, so just write here)

1. We shouldn't use `rte_flow_item_*` for encap data especially `rte_flow_item_eth` because the size is not correct.
We need to use the real header: rte_ether_hdr. So it's better to use all real headers in lib/librte_net/: rte_gtp_hdr, rte_ipv4_hdr, etc.

2. Aslo the gtp_extra_word is missing in raw encap data
the encap _size should be: sizefo(eth) + sizeof(ipv4) + sizeof(udp) + sizeof(gtp) + sizeof(gtp_extra_word) + sizeof(gtp_psc)

3. I got an error on testpmd set raw_encap: "GTP PSC option with extra fields not supported", I think this is a bug in testpmd (cmdline_flow.c:8092). Plz double check.

-Jack

**Comment by ShiriKuzin** [comment]
Hi Jack,
Thank you very much for the review and noticing.
I fixed the structs and adjusted the raw encap data size.
I also added some small fixes to gtp encap and gre encap functions for small things i came across.

Shiri.

**Review by jackmin — CHANGES_REQUESTED** [review]
Hey,

The pattern of `jump` flow is not set so it will use the one set in the previous function `create_gtp_u_encap_flow` because it is called before this function in main.
I saw the raw_encap/ raw_decap actions are created on group 0 so I guess we can just remove the `jump` flow.

**Comment by ShiriKuzin** [comment]
yes correct because we are no matching on GTP PSC, so can use group 0.
thanks for the comment, updated.

**Review by jackmin — APPROVED** [review]
Well done! :)

**Pull request merged**
